name: Iniciador de Workflow

on:
  discussion:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy to your project.

  call-reusable-workflow:
    strategy:
      matrix:
        nodeversion: [Uso1, Uso2, Uso3, Uso4]
    uses: ./.github/workflows/reusable-workflow-MarcoA.yml
    with:
      node: ${{ matrix.nodeversion }}
